---
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

homebrew_taps:
  - homebrew/core
  - homebrew/cask

install_homebrew_if_missing: true
upgrade_homebrew_packages: false

brew_cask_packages:
  - visual-studio-code # comment 
  - google-chrome
  - firefox
  - microsoft-edge
  - sublime-text
  - docker
  - skype
  - discord
  - microsoft-teams
  - zoom
  - bitwarden
  - spotify
  - vagrant
  - vagrant-manager
  - ngrok
  - postman
  - neo4j
  - sourcetree
  - raspberry-pi-imager
  - figma
  - obs # comment for re-install

brew_packages:
  - gnupg
  - chromedriver #comment for re-install
  - dbeaver-community # comment for re-install
  - ngrok # comment for re-install
  - autoconf
  - bash-completion
  - docker-compose
  - git
  - git-lfs
  - go
  - python@3.11
  - python@3.9
  - python@3.8
  - node@18
  - node@16
  - yarn
  - nvm
  - rbenv
  - ruby
  - terraform
  - tree
  - watch
  - wget
  - openssl
  - http-server
  - zsh-history-substring-search
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - pipenv
  - awscli
  - osxfuse
  - sshfs


# https://marketplace.visualstudio.com/vscode
# vscode_extensions:
#   - ms-azuretools.vscode-docker
#   - ms-python.python
#   - ms-python.pylint
#   - ms-python.flake8
#   - ms-toolsai.jupyter
#   - GitHub.vscode-github-actions
#   - ms-vscode.vscode-typescript-next
#   - Vue.vscode-typescript-vue-plugin
#   - msjsdiag.vscode-react-native
#   - dsznajder.es7-react-js-snippets
#   - ms-vscode-remote.remote-ssh
#   - HashiCorp.terraform
#   - redhat.ansible
#   - redhat.vscode-xml
#   - ms-kubernetes-tools.vscode-kubernetes-tools
#   - redhat.vscode-yaml
#   - batisteo.vscode-django
#   - GraphQL.vscode-graphql
#   - GraphQL.vscode-graphql-syntax
#   - formulahendry.auto-close-tag
#   - dbaeumer.vscode-eslint
#   - mikestead.dotenv
#   - hediet.vscode-drawio
#   - AnthonyJGatlin.vscode-cypher-query-language-tools
#   - circleci.circleci

# python_modules:
#   - configparser
#   - pylint
#   - virtualenv
