---
gem_packages: []
# - name: bundler
#   state: present # present/absent/latest, default: present
#   version: "~> 1.15.1" # default: N/A
npm_packages: []
# - name: webpack
#   state: present # present/absent/latest, default: present
#   version: "^2.6" # default: N/A
pip_packages: []
# - name: mkdocs
#   state: present # present/absent/latest, default: present
#   version: "0.16.3" # default: N/A

homebrew_taps:
  - homebrew/core
  - homebrew/cask

install_homebrew_if_missing: true
upgrade_homebrew_packages: false

brew_cask_packages:
  - obs # comment for re-install
  - visual-studio-code # comment 
  - google-chrome
  - firefox
  - microsoft-edge
  - sublime-text
  - docker
  - skype
  - discord
  - microsoft-teams
  - zoom
  - bitwarden
  - spotify
  - vagrant
  - vagrant-manager
  - ngrok
  - postman
  - neo4j
  - sourcetree
  - raspberry-pi-imager
  - figma
  - balenaetcher
  - raycast
  - arc
  - chatgpt
  - warp
  - tor-browser
  - protege

brew_packages:
  - gnupg
  - chromedriver #comment for re-install
  - dbeaver-community # comment for re-install
  - ngrok # comment for re-install
  - sshfs # comment for re-install
  - autoconf
  - bash-completion
  - docker-compose
  - git
  - git-lfs
  - go
  - python@3.12
  - python@3.11
  - python@3.9
  # - python@3.8
  - node@20
  - node@18
  - node@22
  # - node@16
  - yarn
  - nvm
  - rbenv
  - ruby
  - ruby-build
  - terraform
  - tree
  - watch
  - wget
  - openssl
  - http-server
  - zsh-history-substring-search
  - zsh-autosuggestions
  - zsh-syntax-highlighting
  - pipenv
  - awscli
  - cypher-shell
  - helm
  # - osxfuse

# find ids using the command `mas search Tailscale`
mac_apps:
  - name: DaVinci Resolve
    id: 571213070
  - name: Bitwarden
    id: 1352778147         
  - name: OneDrive
    id: 823766827 
  - name: Tailscale
    id: 1475387142
  - name: Microsoft Word
    id: 462054704
  - name: Microsoft Excel
    id: 462058435
  - name: Microsoft PowerPoint
    id: 462062816
  - name: GoPro Quick
    id: 561350520
  - name: GoPro Player
    id: 1460836908
  - name: GoPro Webcam
    id: 6477835262
  - name: Numbers
    id: 409203825
  - name: Pages
    id: 409201541
  - name: Keynote
    id: 409183694
  - name: Bitwarden
    id: 1352778147
  - name: Windows App(RDP)
    id: 1295203466