---
- name: "macbook-setup"
  hosts: localhost

  vars_files:
    - default.config.yml

  pre_tasks:
    - name: Ensuring Homebrew Is Installed
      stat:
        path: /opt/homebrew/bin/brew
      register: homebrew_check

    - name: Fail If Homebrew Is Not Installed and install_homebrew_if_missing Is False
      fail:
        msg: Homebrew is missing...Install from http://brew.sh/
      when:
        - not homebrew_check.stat.exists
        - not install_homebrew_if_missing

    - name: Installing Homebrew
      shell: NONINTERACTIVE=1 /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
      when:
        - not homebrew_check.stat.exists
        - install_homebrew_if_missing

  tasks:
    - import_tasks: tasks/hello-world.yml
    - import_tasks: tasks/development/brew-packages.yml
      name: Install Brew packages
    - import_tasks: tasks/development/extra-packages.yml
      name: "Install pip/npm/gems"