# Install a role from GitHub
- name: ansible-role-visual-studio-code-extensions
  src: https://github.com/gantsign/ansible-role-visual-studio-code-extensions

- name: ansible-role-visual-studio-code
  src: https://github.com/gantsign/ansible-role-visual-studio-code
