- name: Ensure mas is installed
  homebrew:
    name: mas
    state: present

- name: Install Mac App Store apps
  command: mas install "{{ item.id }}"
  loop: "{{ mac_apps }}"
  register: install_results


- name: Debug install results
  debug:
    msg: "Installed app {{ item.item.name }} with ID {{ item.item.id }}."
  loop: "{{ install_results.results }}"