- name: install vs code extensions
  ansible.builtin.include_role:
    name: ansible-role-visual-studio-code
    public: yes
  vars:
    users:
      - username: '{{ ansible_user_id }}'
        visual_studio_code_extensions:
          - ms-azuretools.vscode-docker
          - ms-python.python
          # - ms-python.pylint
          - ms-python.flake8
          - ms-toolsai.jupyter
          - GitHub.vscode-github-actions
          - ms-vscode.vscode-typescript-next
          - Vue.vscode-typescript-vue-plugin
          - msjsdiag.vscode-react-native
          - dsznajder.es7-react-js-snippets
          - ms-vscode-remote.remote-ssh
          - HashiCorp.terraform
          - redhat.ansible
          - redhat.vscode-xml
          - ms-kubernetes-tools.vscode-kubernetes-tools
          - redhat.vscode-yaml
          - batisteo.vscode-django
          - GraphQL.vscode-graphql
          - GraphQL.vscode-graphql-syntax
          - formulahendry.auto-close-tag
          - dbaeumer.vscode-eslint
          - mikestead.dotenv
          - hediet.vscode-drawio
          - AnthonyJGatlin.vscode-cypher-query-language-tools
          - mhutchie.git-graph
          - Equinusocio.vsc-material-theme-icons
          # - circleci.circleci
